### PR TITLE
Added a README example of using the pack-mock-server as a stub.

### PR DESCRIPTION
**Pull request by davesmith00000**
Hi,

You have a great tool here that I nearly ignored and reimplemented due to lack of documentation! :-)

I don't mind if you don't use this change, or if you correct / expand / rewrite it, but please do the poor souls trying to use your lovely software a favour and put in something like this in for us. Also if I've got it wrong please god tell me because it took me ages to piece together it's usage - simple as it is.

I'm not a ruby developer so picking through the source code and trawling google groups for clues was not fun. What I (and people like me) need is simple, vanilla usage examples - hence why I've used curl. You have an example of starting the server but I was like "Great! Now what...?" :-)

I still have no idea what else pact mock service can do!

As a side note, again not being a Ruby developer I tried downloading the standalone release, expanded the zip, recoiled in terror at the volume of stuff in there, and decided it was be less hassle and more obvious to install Ruby with homebrew. I wonder if it would be possible to boil standalone releases down to less files or reorganise the folder structure so that it was blindingly obvious what to do with it. e.g. an executable (the only bit I care about - could even be a shell script to invokes the app delegating arguments to the real programme?), a readme and a folder containing all the other stuff / dragons / voodoo.

Thanks and keep up the good work, I'll be looking at pack broker later so you might get another one of these...

Dave

### CODE REVIEW

**Comment by bethesque** [comment]
Hi Dave, 

Thanks for your PR. While this will work to a certain extent, the mock service is not designed to work this way, and there may be some unexpected issues. Please read this FAQ: https://github.com/realestate-com-au/pact/wiki/FAQ#why-are-the-pacts-generated-and-not-static

I will merge your PR, but add some caveats about it not being the intended use case.

I agree, the standalone package is unfortunately large. It is created using Travelling Ruby, which bundles a version of Ruby inside the package. There's no way to make that smaller that I know of.

The lack of documentation for how to set up interactions manually is because there aren't many people who use it that way. It's generally used with either the Ruby client or the Javascript client, both of which have fairly comprehensive documentation. Are you after something like this gist? https://gist.github.com/bethesque/9d81f21d6f77650811f4

**Comment by bethesque** [comment]
Also, you don't need the X-Pact headers when you're actually executing the request, only when you're setting it up.

**Comment by davesmith00000** [comment]
Hi Beth,

Thanks for the update. Thing is, and I'm not trying to be difficult - but that stuff doesn't actually work for me... I mean quite literally not philosophically, I get errors. :-)

Are you running a newer version or something?

If I run the mock with the control param then I can use it (as submitted) but I have to supply the headers that you've taken off. If I don't run with control then it won't accept a call to PUT / interactions, and if I switch it for a POST and change the headers as per your example I get this:

  curl -X POST \
  -H "Content-Type: application/json" \
  -H "X-Pact-Mock-Service: true" \
  -d @pacts/ExampleConsumer-ExampleProvider.json \
  http://localhost:1234/interactions

Results in:

  E, [2016-01-12T14:50:12.259847 #16406] ERROR -- : Error ocurred in mock service: NoMethodError - undefined method `[]' for nil:NilClass
  E, [2016-01-12T14:50:12.259915 #16406] ERROR -- : /Users/DaviSmi5/.gem/ruby/2.1.3/gems/pact-support-0.5.4/lib/pact/consumer_contract/interaction.rb:22:in `from_hash'
  /Users/DaviSmi5/.gem/ruby/2.1.3/gems/pact-mock_service-0.8.0/lib/pact/mock_service/request_handlers/interaction_post.rb:24:in `respond'
  ...more stacktrace...
  {"message":"Error ocurred in mock service: NoMethodError - undefined method `[]' for nil:NilClass"...

Thank you for the gist, I haven't tried running it as is (sorry I'm just between meetings...) but I shall as soon as I can. In theory it is exactly what I was looking for.

Any ideas?

Thanks,

Dave

**Comment by bethesque** [comment]
I think you may be getting confused between the mock server and the control server. The control server can be used for the administration of one or more mock servers. It accepts only "administration" requests. You send the POST or PUT to /interactions, and it will return a header with the location of the mock server. You then run the tests against that location.

If you just use a mock server directly (which is the normal way), then you need the X-Pact-Mock-Service header to tell the mock server that a given request is an "administration" request, rather than a request from the actual code. When code under test runs, the lack of the X-Pact-Mock-Service header tells the mock server that it is a "real" request.

Please try the gist and let me know if that doesn't work.

**Comment by davesmith00000** [comment]
Hi Beth,

Thanks for the update.

I was trying to use it in the normal way (your second paragraph) and I also thought I might be confused! ...but what you describe is actually exactly what I thought was supposed to happen. I just couldn't make it work.

However, your gist seems to work perfectly so I'll compare it with mine and debug from there.

Thanks again,

Dave

**Comment by davesmith00000** [comment]
Ok I've sussed it. I was trying to upload the pact file that was output by the Pact-JVM specs2 lib. The pact file in your example is more cut down. For example this is the pact-jvm output that doesn't work:

```
{
  "provider" : {
    "name" : "ExampleProvider"
  },
  "consumer" : {
    "name" : "ExampleConsumer"
  },
  "interactions" : [ {
    "providerState" : "Provider service is available",
    "description" : "a request for a greeting",
    "request" : {
      "method" : "GET",
      "path" : "/hello"
    },
    "response" : {
      "status" : 200,
      "body" : "Hello there!"
    }
  } ],
  "metadata" : {
    "pact-specification" : {
      "version" : "2.0.0"
    },
    "pact-jvm" : {
      "version" : "3.0.4"
    }
  }
}
```

...but this works exactly as you said it should.

```
{
  "providerState" : "Provider service is available",
  "description" : "a request for a greeting",
  "request" : {
    "method" : "GET",
    "path" : "/hello"
  },
  "response" : {
    "status" : 200,
    "body" : "Hello there!"
  }
}
```

More stuff for the README.md? ;-)

**Comment by bethesque** [comment]
Yes, POST to /interactions only accepts one interaction. PUT to /interactions accepts a list of interactions. Neither of them were designed to accept a "pact file".

**Comment by bethesque** [comment]
I've put in a link to the gist in the README, and taken out the instructions that didn't work for now so they don't mislead anyone.

**Comment by davesmith00000** [comment]
Yep, again I still hadn't realised that you can use PUT to upload a list - might be work adding to the Gist.

Right, I'll leave you alone Beth. Thank you for all the help, we got there in the end. :+1:

**Pull request merged**
