### PR TITLE
Fix issue with request body and path matching rules generation

### PR DESCRIPTION
**Pull request by MattTYXM**

### CODE REVIEW

**Comment by MattTYXM** [comment]
Working on fixing specs now. I just started learning ruby yesterday so I apologize for not addressing this before the pull request was created.

**Comment by bethesque** [comment]
Sorry @MattTYXM, as mentioned, house move is getting in the way of code time. I have not forgotten about this!

**Comment by MattTYXM** [comment]
Found another issue where the remove interactions endpoint was not clearing the verified interactions which was causing issues when multiple consumer tests were executed against a single running mock service. I modified the endpoint to consider a "keep_verified" parameter that when true will follow the existing logic and when it is false or not passed ALL interactions are removed.

**Comment by bethesque** [comment]
Please submit separate PRs for different changes so they can be evaluated separately.

**Pull request closed without merging**
